import Head from "next/head";
import Dashboard from "@/components/Dashboard/dashboard/index";
import type { GetStaticProps, InferGetStaticPropsType } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Provider } from "react-redux";
import store from "../src/redux/store";

type Props = {
    // Add custom props here
};

export default function Home(
    // eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars, no-use-before-define
    _props: InferGetStaticPropsType<typeof getStaticProps>
) {
    return (
        <Provider store={store}>
            <Head>
                <title>Intello ERP</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Dashboard />
        </Provider>
    );
}

export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => ({
    props: {
        ...(await serverSideTranslations(locale ?? "en")),
    },
});
